#ifndef _CAPTURE_ERRORS_H_
#define _CAPTURE_ERRORS_H_

#define CAP_SUCCESS 0
#define CAP_DEVICE_INIT 1
#define CAP_OPEN_DEVICE 2
#define CAP_COMPILE 3
#define CAP_FILTER 4
#define CAP_HANDLE_INIT 5

#define CAP_PROCESS_INIT 35
#define CAP_PROCESS_FORMAT 36
#define CAP_PROCESS_OPEN 37
#define CAP_PROCESS_OPEN_DIR 38
#endif  // _CAPTURE_ERRORS_H_